{"name": "test_del_group", "status": "broken", "statusDetails": {"message": "AttributeError: module 'pytest' has no attribute 'allure'", "trace": "app = <fixture.application.Application object at 0x040705F8>\ndb = <fixture.db.dBFixture object at 0x040703E8>, check_ui = False\n\n    def test_del_group(app, db, check_ui):\n        if len(db.get_group_list()) == 0:\n            app.group.create(Group(name=\"test1\", header=\"test1\", footer=\"test1\"))\n>       with pytest.allure.step('Given a group list'):\nE       AttributeError: module 'pytest' has no attribute 'allure'\n\ntests\\test_del_group.py:9: AttributeError"}, "start": 1581258210948, "stop": 1581258210950, "uuid": "56dad383-5ccd-466c-8e67-abbeb52452e0", "historyId": "5f065342bed111c7bd131668b6495282", "testCaseId": "1033ae450c4382527a843ea3510a402d", "fullName": "tests.test_del_group#test_del_group", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_del_group"}, {"name": "host", "value": "idea-PC"}, {"name": "thread", "value": "5484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_del_group"}]}